### ISSUE TITLE
qimqim

### ISSUE THREAD

**Issue by infinteycode** [xqm32/LeetCode#1]
![image](https://github.com/xqm32/LeetCode/assets/169935024/0fe8a953-dc76-4878-9acd-85cbd08e88ae)

**Comment by xqm32** [comment]
好像是之前的论坛域名商倒闭辣，论坛换了个域名。同人太多了，我直接写了个脚本批量改了。

It seems that the previous domain name provider of the forum went out of business and the forum changed its domain name. There are too many fan works, so I just wrote a script and changed them in batches.
